"""Add payment models

Revision ID: 03a04ff3cc27
Revises: 3562792b8571
Create Date: 2026-06-20 18:02:16.982849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03a04ff3cc27'
down_revision: Union[str, None] = '3562792b8571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=256), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('overpayment_credits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', postgresql.ENUM('UNRESOLVED', 'REFUNDED', 'ACKNOWLEDGED_KEEP', name='overpayment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overpayment_credits_user_id'), 'overpayment_credits', ['user_id'], unique=False)
    op.create_table('payment_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('network', sa.String(length=64), nullable=True),
    sa.Column('target_value', sa.Text(), nullable=False),
    sa.Column('rate_locked_usd_to_crypto', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('amount_expected_crypto', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('bitnob_response_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_targets_invoice_id'), 'payment_targets', ['invoice_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('payment_target_id', sa.UUID(), nullable=False),
    sa.Column('tx_hash', sa.String(length=256), nullable=False),
    sa.Column('amount_received_crypto', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('amount_received_usd_equiv', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('network', sa.String(length=64), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('bitnob_event_id', sa.String(length=256), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['payment_target_id'], ['payment_targets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash', 'invoice_id', name='uq_payments_tx_invoice')
    )
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_payment_targets_invoice_id'), table_name='payment_targets')
    op.drop_table('payment_targets')
    op.drop_index(op.f('ix_overpayment_credits_user_id'), table_name='overpayment_credits')
    op.drop_table('overpayment_credits')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
