"""Initial migration

Revision ID: 3562792b8571
Revises: 
Create Date: 2026-06-20 16:57:22.814224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3562792b8571'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_email', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING', 'PARTIALLY_PAID', 'PAID', 'OVERPAID', 'EXPIRED', 'CANCELLED', 'REFUNDED', name='invoice_status'), nullable=False),
    sa.Column('bitnob_reference', sa.String(), nullable=False),
    sa.Column('amount_received_usd_equiv', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('overpaid_amount_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bitnob_reference')
    )
    op.create_index('idx_invoices_status', 'invoices', ['status'], unique=False)
    op.create_index('idx_invoices_user_id', 'invoices', ['user_id'], unique=False)
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index('idx_invoices_user_id', table_name='invoices')
    op.drop_index('idx_invoices_status', table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
