"""make payment target nullable

Revision ID: 5ecb075a4179
Revises: 89621103495f
Create Date: 2026-06-21 18:12:19.697809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ecb075a4179'
down_revision: Union[str, None] = '89621103495f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'payment_target_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'payment_target_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
