"""busha_branch_models

Revision ID: 89621103495f
Revises: 
Create Date: 2026-06-21 17:06:59.494279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89621103495f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_dedup_key', sa.String(length=512), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_dedup_key')
    )
    op.create_index('idx_webhook_events_event_type', 'webhook_events', ['event_type'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_email', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING', 'PARTIALLY_PAID', 'PAID', 'OVERPAID', 'EXPIRED', 'CANCELLED', 'REFUNDED', name='invoice_status'), nullable=False),
    sa.Column('busha_reference', sa.String(), nullable=False),
    sa.Column('busha_link_id', sa.String(), nullable=True),
    sa.Column('amount_received_usd_equiv', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('overpaid_amount_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('busha_link_id'),
    sa.UniqueConstraint('busha_reference')
    )
    op.create_index('idx_invoices_busha_reference', 'invoices', ['busha_reference'], unique=True)
    op.create_index('idx_invoices_status', 'invoices', ['status'], unique=False)
    op.create_index('idx_invoices_user_id', 'invoices', ['user_id'], unique=False)
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.create_table('overpayment_credits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', postgresql.ENUM('UNRESOLVED', 'REFUNDED', 'ACKNOWLEDGED_KEEP', name='overpayment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overpayment_credits_user_id'), 'overpayment_credits', ['user_id'], unique=False)
    op.create_table('payment_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('network', sa.String(length=64), nullable=True),
    sa.Column('target_value', sa.Text(), nullable=False),
    sa.Column('busha_payment_request_id', sa.String(length=256), nullable=False),
    sa.Column('rate_locked_usd_to_crypto', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('amount_expected_crypto', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('busha_response_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('busha_payment_request_id')
    )
    op.create_index('idx_payment_targets_invoice_active', 'payment_targets', ['invoice_id', 'is_active'], unique=False)
    op.create_index('idx_payment_targets_invoice_id', 'payment_targets', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_targets_invoice_id'), 'payment_targets', ['invoice_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('payment_target_id', sa.UUID(), nullable=False),
    sa.Column('tx_hash', sa.String(length=256), nullable=False),
    sa.Column('amount_received_crypto', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('amount_received_usd_equiv', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('network', sa.String(length=64), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('busha_payment_request_id', sa.String(length=256), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_target_id'], ['payment_targets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash', 'invoice_id', name='uq_payments_tx_invoice')
    )
    op.create_index('idx_payments_invoice_id', 'payments', ['invoice_id'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_invoice_id'), 'receipts', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_receipts_payment_id'), 'receipts', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipts_payment_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_invoice_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index('idx_payments_invoice_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_payment_targets_invoice_id'), table_name='payment_targets')
    op.drop_index('idx_payment_targets_invoice_id', table_name='payment_targets')
    op.drop_index('idx_payment_targets_invoice_active', table_name='payment_targets')
    op.drop_table('payment_targets')
    op.drop_index(op.f('ix_overpayment_credits_user_id'), table_name='overpayment_credits')
    op.drop_table('overpayment_credits')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index('idx_invoices_user_id', table_name='invoices')
    op.drop_index('idx_invoices_status', table_name='invoices')
    op.drop_index('idx_invoices_busha_reference', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('idx_webhook_events_event_type', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
